### ISSUE TITLE
Refactor racePosition function

### ISSUE THREAD

**Issue by shiryz** [FACN4/week9-Race-Home#26]
This function can be refactored in the following way:
- take out this if statement 
```js
if (this.state.position[0] > 750 || this.state.position[1] > 750) {
      return;
    }
```
and put it on top, so it would return and not execute any code if it doesn't have to

- `setState` once, you'll have to save a position variable which would be one of 2 states depending on the character
```js
let position = ...
if (event.charCode === 49) {
   position = [prevState.position[0] + 5, prevState.position[1]];
} else if (event.charCode === 48) {
   position = [prevState.position[0], prevState.position[1] + 5];
}
```
and you `setState` with your position variable

This will make this function a lot more readable

**Comment by BenNewman90** [comment]
Good point. Updated.
